"use client";

import { useEffect, useRef, useState } from "react";
import sdk from "@stackblitz/sdk";
import { Loader2, ExternalLink, RefreshCw } from "lucide-react";

interface StackBlitzPreviewProps {
  files: Record<string, string>;
  projectName?: string;
}

export function StackBlitzPreview({ files, projectName = "odeta-project" }: StackBlitzPreviewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const vmRef = useRef<ReturnType<typeof sdk.embedProject> | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const embedId = useRef(0);

  useEffect(() => {
    if (!containerRef.current || Object.keys(files).length === 0) return;

    const currentId = ++embedId.current;
    setIsLoading(true);
    setError(null);

    // Small delay to let DOM settle
    const timer = setTimeout(async () => {
      if (currentId !== embedId.current) return;
      if (!containerRef.current) return;

      try {
        const vm = await sdk.embedProject(
          containerRef.current,
          {
            title: projectName,
            description: "Generated by Odeta",
            template: "node",
            files,
          },
          {
            openFile: "src/app/page.tsx",
            view: "preview",
            hideNavigation: true,
            hideDevTools: true,
            theme: "light",
            height: "100%",
          }
        );
        vmRef.current = vm as any;
        setIsLoading(false);
      } catch (err: unknown) {
        if (currentId !== embedId.current) return;
        const message = err instanceof Error ? err.message : "Failed to load preview";
        setError(message);
        setIsLoading(false);
      }
    }, 500);

    return () => clearTimeout(timer);
  }, [files, projectName]);

  if (Object.keys(files).length === 0) {
    return (
      <div className="flex items-center justify-center h-full text-center px-6">
        <div>
          <div className="w-12 h-12 rounded-2xl bg-gray-100 flex items-center justify-center mx-auto mb-3">
            <Loader2 className="w-5 h-5 text-gray-400" />
          </div>
          <p className="text-sm text-gray-500">Your app preview will appear here as it&#39;s built</p>
        </div>
      </div>
    );
  }

  return (
    <div className="relative w-full h-full">
      {isLoading && (
        <div className="absolute inset-0 flex items-center justify-center bg-white z-10">
          <div className="text-center">
            <Loader2 className="w-6 h-6 text-blue-500 animate-spin mx-auto mb-2" />
            <p className="text-sm text-gray-500">Loading preview...</p>
          </div>
        </div>
      )}

      {error && (
        <div className="absolute inset-0 flex items-center justify-center bg-white z-10">
          <div className="text-center px-6">
            <p className="text-sm text-red-500 mb-3">{error}</p>
            <button
              onClick={() => window.location.reload()}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              <RefreshCw className="w-3 h-3" />
              Retry
            </button>
          </div>
        </div>
      )}

      <div ref={containerRef} className="w-full h-full" />
    </div>
  );
}

// Helper: open project in a new StackBlitz tab
export function openInStackBlitz(files: Record<string, string>, projectName: string) {
  sdk.openProject(
    {
      title: projectName,
      description: "Generated by Odeta",
      template: "node",
      files,
    },
    { openFile: "src/app/page.tsx" }
  );
}
